defaults:
  - actor_critic.yaml
  - _self_

name: "SAC"
horizon_len: 1
memory_size: 1e6
batch_size: 4096
nstep: 1
tau: 0.05
gamma: 0.99
warm_up: 32
act_class: TanhDiagGaussianMLPPolicy
cri_class: DoubleQ
eval_freq: 100
alpha_lr: 0.005

update_times: 8
no_tgt_actor: True
alpha: null